import os
import traceback
from datetime import datetime
from pathlib import Path

from autogen_agentchat.teams import RoundRobinGroupChat
from autogen_agentchat.conditions import TextMessageTermination, MaxMessageTermination

from src.config import get_llm_model_client, ResponseLevel, RESPONSE_LEVEL_PROMPTS
from src.agents.debate_agents import (
    ConsultantAgent,
    ArchitectAgent,  # Adversarial Architect — renamed from AdversarialArchitectAgent
)

# ── Agent display config ───────────────────────────────────────────────────────
AGENT_META = {
    "Consultant": {
        "icon":  "🤝",
        "label": "Lead Technical Consultant",
        "color_tag": "consultant",
    },
    "Architect": {
        "icon":  "🏗️",
        "label": "Adversarial System Architect",  # display label retains Adversarial
        "color_tag": "architect",
    },
}

TRANSCRIPT_DIR = Path("docs/debate_history")


class DebateOrchestrator:
    """
    This Orchestrator class ties the agents together using AutoGen 0.4's 
    `RoundRobinGroupChat` team primitive.
    """
    def __init__(self, requirement_topic: str, max_rounds: int = 6,
                 response_level: ResponseLevel = ResponseLevel.ADVANCED,
                 num_solutions: int = 1):
        self.topic = requirement_topic
        self.max_rounds = max_rounds
        self.response_level = response_level
        self.num_solutions = num_solutions
        
        # Instantiate the 0.4 Model Client
        self.model_client = get_llm_model_client()
        
        # Instantiate our custom agent wrapper classes, passing the verbosity level
        self.consultant_wrapper = ConsultantAgent(self.model_client, response_level)
        self.architect_wrapper = ArchitectAgent(self.model_client, response_level)
        
        # Extract the underlying AutoGen 0.4 AssistantAgents
        self.consultant = self.consultant_wrapper.agent
        self.architect = self.architect_wrapper.agent

    # ── Transcript helpers ─────────────────────────────────────────────────────

    def _build_transcript_header(self, timestamp: str) -> str:
        """Returns the markdown header block for the transcript file."""
        level = self.response_level.value.upper()
        topic_snippet = self.topic[:200] + ("..." if len(self.topic) > 200 else "")
        return (
            f"# 🧠 Group Debate Transcript\n\n"
            f"> **Generated:** {timestamp}  \n"
            f"> **Response Level:** `{level}`  \n"
            f"> **Max Rounds:** `{self.max_rounds}`  \n\n"
            f"---\n\n"
            f"## 📋 Debate Topic\n\n"
            f"{topic_snippet}\n\n"
            f"---\n\n"
        )

    def _format_message_block(self, source: str, content: str, turn: int) -> str:
        """Returns a beautifully formatted markdown block for one agent message."""
        meta = AGENT_META.get(source, {"icon": "🤖", "label": source})
        icon  = meta["icon"]
        label = meta["label"]
        divider = "═" * 60

        return (
            f"\n## {icon} Turn {turn} — {label}\n\n"
            f"```\n{divider}\n```\n\n"
            f"{content}\n\n"
            f"---\n\n"
        )

    def _build_transcript_footer(self, total_turns: int, concluded_by: str) -> str:
        """Returns the closing section of the transcript."""
        return (
            f"## ✅ Debate Concluded\n\n"
            f"| Field | Value |\n"
            f"|---|---|\n"
            f"| Total turns | `{total_turns}` |\n"
            f"| Concluded by | `{concluded_by}` |\n"
            f"| Response level | `{self.response_level.value.upper()}` |\n\n"
            f"---\n\n"
            f"*Transcript generated by **Group Debate Agents** (AutoGen 0.4)*\n"
        )

    async def run_phase1_options(self):
        """Phase 1: Generates options if num_solutions > 1 and yields messages."""
        if self.num_solutions <= 1:
            return

        options_team = RoundRobinGroupChat(
            participants=[self.consultant],
            termination_condition=MaxMessageTermination(max_messages=2)
        )
        
        options_task = (
            f"REQUIREMENT:\n{self.topic}\n\n"
            f"Propose exactly {self.num_solutions} distinct architecture solutions.\n"
            "Each solution must have a ## heading with an emoji and one short summary paragraph.\n"
            "Label them clearly: ## 🏗️ Option 1: ..., ## ⚡ Option 2: ...\n"
            "Do NOT go into deep detail — brief summaries only.\n"
            "Use **bold** for key technology names.\n"
            "FORMAT: Respond in clean Markdown with emoji headings and bold terms. No plain text."
        )
        
        consultant_options_response = ""
        async for msg in options_team.run_stream(task=options_task):
            if hasattr(msg, "source") and msg.source.lower() == "consultant":
                consultant_options_response = msg.content
                yield msg

    async def run_phase2_debate(self, consultant_options_response: str = "", user_opinion: str = ""):
        """Phase 2: Runs the actual debate based on options and user preference."""
        text_termination = TextMessageTermination("I APPROVE THIS PLAN")
        max_message_termination = MaxMessageTermination(max_messages=self.max_rounds + 1)
        termination_condition = text_termination | max_message_termination

        if self.num_solutions > 1:
            initial_prompt = (
                f"REQUIREMENT:\n{self.topic}\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                "DEBATE FLOW\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
                f"CONSULTANT'S PROPOSED OPTIONS:\n{consultant_options_response}\n\n"
            )
            
            if user_opinion:
                initial_prompt += f"USER'S PREFERENCE/OPINION: {user_opinion}\n\n"
            else:
                initial_prompt += "USER'S PREFERENCE/OPINION: (User skipped. Architect, you alone must decide the best option.)\n\n"
            
            initial_prompt += (
                "📌 STEP 1 — Architect (your FIRST turn):\n"
                "   Review the options along with the User's preference (if provided).\n"
                "   Select the SINGLE strongest option and state clearly: 'I SELECT Option [N]'.\n"
                "   Explain why it is the best choice (agreeing or disagreeing with the user if applicable).\n"
                "   Then raise your first set of critical concerns about the selected option.\n\n"
                
                "📌 STEP 2 — Consultant (all SUBSEQUENT turns):\n"
                "   Acknowledge the Architect's selection. From now on, discuss THAT solution ONLY.\n"
                "   Produce a FULLY DETAILED plan for the selected solution using active Response Level formatting.\n"
                "   Address the Architect's concerns.\n\n"
                
                "📌 STEP 3 — Architect (all SUBSEQUENT turns):\n"
                "   Deep-dive critique the selected solution.\n"
                "   Use What* challenge questions with <mark>**What ...**</mark> highlight format.\n"
                "   When satisfied, output: I APPROVE THIS PLAN\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                "⚠️ MANDATORY FORMAT OVERRIDE — ACTIVE RESPONSE LEVEL:\n"
                f"{RESPONSE_LEVEL_PROMPTS[self.response_level.value]}\n"
                "📌 This overrides everything above. Follow this format for EVERY response.\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            )
            
            team = RoundRobinGroupChat(
                participants=[self.architect, self.consultant],  # Architect goes first!
                termination_condition=termination_condition
            )
            
        else:
            initial_prompt = (
                f"REQUIREMENT:\n{self.topic}\n\n"
                "Consultant, please draft the absolute best, most detailed initial plan following Response Level formatting. "
                "Architect, review the plan completely once submitted and raise concerns if any. "
                "Consultant, revise based on the Architect's feedback.\n\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                "⚠️ MANDATORY FORMAT OVERRIDE — ACTIVE RESPONSE LEVEL:\n"
                f"{RESPONSE_LEVEL_PROMPTS[self.response_level.value]}\n"
                "📌 This overrides everything above. Follow this format for EVERY response.\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
            )
            team = RoundRobinGroupChat(
                participants=[self.consultant, self.architect],  # Consultant goes first
                termination_condition=termination_condition
            )

        async for message in team.run_stream(task=initial_prompt):
            if hasattr(message, "source") and hasattr(message, "content"):
                if message.source.lower() == "user":
                    continue
                yield message

    # ── LEGACY CLI WRAPPER ───────────────────────────────────────────────────
    async def start_debate(self):
        """CLI wrapper that uses the new phase 1 and phase 2 generators."""
        print("\n" + "="*60)
        print("STARTING DEBATE ORCHESTRATION (CLI Mode)")
        print(f"Topic: {self.topic}")
        print(f"Max Turns Allowed: {self.max_rounds}")
        print(f"Response Level   : {self.response_level.value.upper()}")
        print("="*60 + "\n")

        # Prepare transcript file
        TRANSCRIPT_DIR.mkdir(exist_ok=True)
        now = datetime.now()
        timestamp_str = now.strftime("%Y-%m-%d %H:%M:%S")
        file_stamp    = now.strftime("%Y%m%d_%H%M%S")
        level_tag     = self.response_level.value
        transcript_path = TRANSCRIPT_DIR / f"debate_{file_stamp}_{level_tag}.md"

        transcript_lines: list[str] = [self._build_transcript_header(timestamp_str)]
        turn_count = 0
        concluded_by = "max rounds reached"

        print(f"📄 Transcript will be saved to: {transcript_path}\n")

        # Phase 1
        consultant_options_response = ""
        if self.num_solutions > 1:
            print(f"\n[ORCHESTRATOR] Asking Consultant to generate {self.num_solutions} distinct solutions first...")
            async for msg in self.run_phase1_options():
                consultant_options_response = msg.content
                meta = AGENT_META.get(msg.source, {"icon": "🤖"})
                print(f"\n{meta['icon']} [{msg.source.upper()} - Initial Options]:\n{msg.content}")

            # Turn 1 is technically Consultant's options in transcript
            turn_count += 1
            transcript_lines.append(self._format_message_block("Consultant", consultant_options_response, turn_count))

        # Human Input
        user_opinion = ""
        if self.num_solutions > 1:
            print("\n" + "═" * 60)
            print("👤 HUMAN-IN-THE-LOOP")
            print("═" * 60)
            user_opinion = input("\nWhat are your thoughts on these options? (Press ENTER to skip): ").strip()
            if user_opinion:
                transcript_lines.append(f"\n## 👤 Human-in-the-Loop Feedback\n\n> {user_opinion}\n\n---\n\n")

        # Phase 2
        try:
            async for msg in self.run_phase2_debate(consultant_options_response, user_opinion):
                source = msg.source
                content = msg.content
                
                meta  = AGENT_META.get(source, {"icon": "🤖", "label": source})
                print(f"\n{meta['icon']} [{source.upper()}]:\n{content}")

                turn_count += 1
                transcript_lines.append(self._format_message_block(source, content, turn_count))

                if "I APPROVE THIS PLAN" in content:
                    concluded_by = f"{source} approved the plan"

                transcript_path.write_text("".join(transcript_lines), encoding="utf-8")
                
        except Exception as e:
            print(f"Encountered an error in the debate structure: {e}")
            traceback.print_exc()
        finally:
            transcript_lines.append(self._build_transcript_footer(turn_count, concluded_by))
            transcript_path.write_text("".join(transcript_lines), encoding="utf-8")

            print("\n" + "="*60)
            print("DEBATE CONCLUDED")
            print(f"📄 Transcript saved → {transcript_path}")
            print("="*60 + "\n")
